<%@ Register Tagprefix="Selectors" Namespace="CMStTrafficSafety" %>

<%@ Register Assembly="AjaxControlToolkit" Namespace="AjaxControlToolkit" TagPrefix="asp" %>
<%@ Register Tagprefix="CMStTrafficSafety" TagName="ThemeButton" Src="../Shared/ThemeButton.ascx" %>

<%@ Register Tagprefix="BaseClasses" Namespace="BaseClasses.Web.UI.WebControls" Assembly="BaseClasses" %>
<%@ Page Language="vb" EnableEventValidation="false" AutoEventWireup="false" CodeFile="SignIn.aspx.vb" Culture="en-US" MasterPageFile="../Master Pages/SIGNIN_MASTER.master" Inherits="CMStTrafficSafety.UI.SignIn" %><asp:Content id="Content" ContentPlaceHolderID="PageContent" runat="server">
    <a id="StartOfPageContent"></a>
          <table class="dv" cellpadding="0" cellspacing="0" border="0"><tr><td></td><td class="dh">
<table cellpadding="0" cellspacing="0" border="0" width="100%"><tr><td class="dhel"><img src="../Images/space.gif" alt="" /></td><td class="dheci" valign="middle"><asp:CollapsiblePanelExtender id="SignInCPExtender" runat="server" TargetControlid="SignInCollapsibleRegion" ExpandControlID="SignInToggleIcon" CollapseControlID="SignInToggleIcon" ImageControlID="SignInToggleIcon" ExpandedImage="../images/icon_panelcollapse.gif" CollapsedImage="../images/icon_panelexpand.gif" SuppressPostBack="true" />
                        <asp:ImageButton id="SignInToggleIcon" runat="server" ToolTip="<%# GetResourceValue(&quot;Btn:ExpandCollapse&quot;, &quot;CMStTrafficSafety&quot;) %>" causesvalidation="False" imageurl="../images/icon_panelcollapse.gif" />
            </td><td class="dhb"><table cellpadding="0" cellspacing="0" border="0"><tr><td class="dht" valign="middle"><asp:Literal runat="server" id="DialogTitle" Text="&lt;%# GetResourceValue(&quot;Txt:SignIn&quot;, &quot;CMStTrafficSafety&quot;) %>">	</asp:Literal></td></tr></table>
</td><td class="dher"><img src="../Images/space.gif" alt="" /></td></tr></table>
</td><td class="dh"></td></tr><tr><td style="width:auto;">&nbsp;</td><td class="dBody1" style="padding-left:8px; padding-right:8px; padding-top:4px;width:400px;border:1px solid #ccc;"><%= SystemUtils.GenerateEnterKeyCaptureBeginTag(FindControlRecursively("OKButton")) %><asp:panel id="SignInCollapsibleRegion" runat="server"><table cellpadding="0" cellspacing="0" border="0" width="325"><tr><td style="padding-left:8px; padding-right:8px; padding-top:4px;width:300px;"><table cellpadding="1" cellspacing="1" border="0"><tr><td colspan="4" style="height: 5px;"></td></tr><tr><td colspan="4"><asp:Label runat="server" id="LoginMessage">	</asp:Label></td></tr><tr><td colspan="4" style="height: 5px;"></td></tr><tr><td class="field_label" style="width:100px;"><asp:Label runat="server" id="UserNameLabel" Text="&lt;%# GetResourceValue(&quot;Txt:UserName&quot;, &quot;CMStTrafficSafety&quot;) %>">	</asp:Label></td><td class="field_value" style="width:200px;"><asp:TextBox runat="server" id="UserName" columns="50" commandname="TextBoxUserName_Command" cssclass="field_input" width="200px">	</asp:TextBox>
	<asp:RequiredFieldValidator runat="server" id="UserNameRequiredFieldValidator" ControlToValidate="UserName" ErrorMessage="&lt;%# GetResourceValue(&quot;Val:ValueIsRequired&quot;, &quot;CMStTrafficSafety&quot;).Replace(&quot;{FieldName}&quot;, &quot;UserName&quot;) %>" display="None" enabled="True">	</asp:RequiredFieldValidator></td><td style="width:20px;padding-left:10px;"><asp:CheckBox runat="server" id="RememberUserName" commandname="CheckBoxUN_Command" postback="True">	</asp:CheckBox></td><td class="field_label" style="width:100px;padding: 2px 4px 2px 4px;"><asp:Label runat="server" id="RememberUserNameLabel" Text="&lt;%# GetResourceValue(&quot;Txt:RememberUN&quot;, &quot;CMStTrafficSafety&quot;) %>">	</asp:Label></td></tr><tr><td colspan="4" style="height: 1px;"></td></tr><tr><td class="field_label"><asp:Label runat="server" id="PasswordLabel" Text="&lt;%# GetResourceValue(&quot;Txt:Password&quot;, &quot;CMStTrafficSafety&quot;) %>">	</asp:Label></td><td class="field_value"><asp:TextBox runat="server" id="Password" columns="50" commandname="TextBoxPassword_Command" cssclass="field_input" textmode="Password" width="200px">	</asp:TextBox>
	<asp:RequiredFieldValidator runat="server" id="PasswordRequiredFieldValidator" ControlToValidate="Password" ErrorMessage="&lt;%# GetResourceValue(&quot;Val:ValueIsRequired&quot;, &quot;CMStTrafficSafety&quot;).Replace(&quot;{FieldName}&quot;, &quot;Password&quot;) %>" display="None" enabled="True">	</asp:RequiredFieldValidator></td><td style="width:20px;padding-left:10px;"><asp:CheckBox runat="server" id="RememberPassword" commandname="CheckBoxPass_Command" postback="True">	</asp:CheckBox></td><td class="field_label"><asp:Label runat="server" id="RememberPasswordLabel" Text="&lt;%# GetResourceValue(&quot;Txt:RememberPassword&quot;, &quot;CMStTrafficSafety&quot;) %>">	</asp:Label></td></tr><tr><td></td><td class="fyp_link"><asp:LinkButton runat="server" id="EmailLinkButton" causesvalidation="False" commandname="ForgotUser" consumers="page" text="&lt;%# GetResourceValue(&quot;Txt:ForgotPassword&quot;, &quot;CMStTrafficSafety&quot;) %>">		
	</asp:LinkButton></td><td style="width:20px;padding-left:10px;"><asp:CheckBox runat="server" id="AutomaticallySignIn" commandname="CheckBoxAutoLogin_Command" postback="True">	</asp:CheckBox></td><td class="field_label"><asp:Label runat="server" id="AutomaticallySignInLabel" Text="&lt;%# GetResourceValue(&quot;Txt:AutoLogin&quot;, &quot;CMStTrafficSafety&quot;) %>">	</asp:Label></td></tr><tr><td style="height: 5px;"></td><td style="height: 5px;" colspan="3"><asp:Label runat="server" id="PasswordMessage">	</asp:Label></td></tr></table>
</td></tr><tr><td><table cellpadding="0" cellspacing="0" border="0" style="padding-top:10px; padding-bottom:5px;" align="center"><tr><td style="width:1px;"><CMStTrafficSafety:ThemeButton runat="server" id="OKButton" button-causesvalidation="True" button-commandname="Login" button-text="&lt;%# GetResourceValue(&quot;Btn:OK&quot;, &quot;CMStTrafficSafety&quot;) %>" button-tooltip="&lt;%# GetResourceValue(&quot;Btn:OK&quot;, &quot;CMStTrafficSafety&quot;) %>"></CMStTrafficSafety:ThemeButton></td><td><CMStTrafficSafety:ThemeButton runat="server" id="CancelButton" button-causesvalidation="False" button-commandname="Redirect" button-text="&lt;%# GetResourceValue(&quot;Btn:Cancel&quot;, &quot;CMStTrafficSafety&quot;) %>" button-tooltip="&lt;%# GetResourceValue(&quot;Btn:Cancel&quot;, &quot;CMStTrafficSafety&quot;) %>"></CMStTrafficSafety:ThemeButton></td></tr></table>
</td></tr></table></asp:panel>
<%= SystemUtils.GenerateEnterKeyCaptureEndTag(FindControlRecursively("OKButton")) %></td><td style="width:auto;">&nbsp;</td></tr></table><div id="detailPopup" class="detailRolloverPopup" onmouseout="detailRolloverPopupClose();" onmouseover="clearTimeout(gPopupTimer);"></div>          
        <asp:ValidationSummary id="ValidationSummary1" ShowMessageBox="true" ShowSummary="false" runat="server"></asp:ValidationSummary>
    </asp:Content>
          